steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/Volunteer-Management/imagetest1', '.']

# Push the Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/Volunteer-Management/imagetest1']

# Deploy the Docker container
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-d', '-p', '80:80', 'gcr.io/Volunteer-Management/imagetest1']